#Parametros: van dentro de los parentesis cuando se declara la funcion

def hello(greet,name):
    print(f"{greet}, {name}!")
# Argumentos: van dentro de los parentesis cuando se llama a la funcion
hello("Hola","Pepe")
hello("Hello","Alice")
hello("Bonjour","Marie")
hello("Ciao","Luca")
hello("Hallo","Hans")
hello("Namaste","Aarav")
hello("Salam","Aisha")
hello("Konnichiwa","Yuki")
hello("Olá","João")
hello("Hej","Anna")
hello("Zdravstvuyte","Ivan")
hello("Merhaba","Emre")
hello("Sawubona","Thandi")
hello("Sawasdee","Nok")
hello("Xin chào","Lan")
hello("Shalom","David")
hello("Hej","Lars")
hello("Cześć","Kasia")
hello("Dia dhuit","Siobhán")
hello("Yassas","Nikos")
hello("Aloha","Kimo")
hello("Salve","Lucia")
hello("Tere","Katrin")
hello("Sannu","Amina")
hello("Hallo","Johan")
